#! /bin/sh
# -------------------------------------------------
# file: ${DOTFILES}/startup/xbindkeysrc
# author    jls - http://sjorssparreboom.nl
# -------------------------------------------------

#keystate_numlock = enable
#keystate_capslock = enable
#keystate_scrolllock= enable

# Volume settings
# -------------------------------------------------

# Muter/UnMute
# -------------------------------------------------
"amixer set "Master" toggle"
m:0x00 + c:121
XF86AudioMute

# Volume up
# -------------------------------------------------
"amixer set "Master" 5%+"
m:0x0 + c:123
XF86AudioRaiseVolume

# Volume down
# -------------------------------------------------
"amixer set "Master" 5%-"
m:0x0 + c:122
XF86AudioLowerVolume

# Suspend to ram
# -------------------------------------------------
"sudo pm-suspend"
m:0x0 + c:150
XF86Sleep

# Brightness up
# -------------------------------------------------
"xbacklight -inc 10"
m:0x0 + c:233
XF86MonBrightnessUp

# Brightness down
# -------------------------------------------------
"xbacklight -dec 10"
m:0x0 + c:232
XF86MonBrightnessDown
