# -- Meta ---------------------------------------------------------------------
# -- File:   ${DOTFILES}/startup/xinitrc
# -- Author: SirJls - http://sjorssparreboom.nl
# -----------------------------------------------------------------------------

# -- Initialize ---------------------------------------------------------------

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if ( hash xset ); then
  xset r rate 150 25
  xset s off -dpms
  xset s noblank
fi

if  ( hash autocutsel ); then
    autocutsel -fork &
    autocutsel -selection PRIMARY -fork &
fi

if ( hash xmodmap ); then
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
fi

# -- Start --------------------------------------------------------------------

exec $SCRIPTS/i3-start

# vim:set ft=xinitrc noet sts=2 sw=2 ts=2 tw=79:
