# ----------------------------------------------------
# file:   ${DOTFILES}/startup/xinitrc
# author: jls - http://sjorssparreboom.nl
# ----------------------------------------------------

# init
# ----------------------------------------------------
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# xset settings
# ----------------------------------------------------
if ( hash xset ); then
  xset r rate 150 25
  xset s off -dpms
  xset s noblank
fi

# clipboard synching
# ----------------------------------------------------
if  ( hash autocutsel ); then
    autocutsel -fork &
    autocutsel -selection PRIMARY -fork &
fi

# disable CapsLock & map to Escape
# ----------------------------------------------------
if ( hash xmodmap ); then
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
fi

# Start i3 on tty1
# ----------------------------------------------------
exec $SCRIPTS/i3-start
